spring:
  cloud:
    stream:
      bindings:
        input:
          destination: rjug.dest
          group: rjug.stream
          consumer:
            concurrency: 2
          content-type: text/plain
        output:
          destination: rjug.dest.out
      kafka:
        bindings:
          input:
            consumer:
              enable-dlq: true

