spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
  cloud:
    stream:
      bindings:
        input:
          destination: rjug.dest
          group: rjug.stream
          consumer:
            concurrency: 2
            header-mode: raw
          content-type: text/plain
        output:
          destination: rjug.dest.out
          producer:
            header-mode: raw
      kafka:
        bindings:
          input:
            consumer:
              enable-dlq: true

